### ISSUE TITLE
Consistency in error payload

### ISSUE THREAD

**Issue by bijujoseph** [CMSgov/qpp-file-upload-api-client#16]
At the moment we get errors in different shapes. Sometimes the error is a single self-contained object, (example validate with 1 error), and some other times `details` as an array (example validate with multiple errors). 
So the idea here is to have transformations to expose a consistent error payload back. 
 Example: Error with details always an array. 
Whomsoever is working on this task must go through the errors thrown by following, to come up with a consistent response payload structure. 
 /validate (post)
 /submissions (get)
 /measurement-sets/ (post)
 /measurement-sets/:id (put)

**Comment by joshboley** [comment]
This work is done for the current implementation.  We will handle QRDA error formatting in #12
