### ISSUE TITLE
Gitleaks-Action vs breaking update

### ISSUE THREAD

**Issue by weineran** [CMSgov/qpp-file-upload-api-client#170]
Hi CMSgov!
We noticed that you are not pinning your gitleaks-action version, but rather [using gitleaks-action@master](https://github.com/CMSgov/qpp-file-upload-api-client/blob/ac41419e26aa84dd96bcbeea186e72ad8a8872a8/.github/workflows/git-leaks.yml#L13). We wanted to give you a heads up that we are planning to merge gitleaks-action@v2 to master soon, which is a breaking update. See more details [here](https://github.com/gitleaks/gitleaks-action#-announcement). By the way, we think you'll love [v2's features](https://github.com/gitleaks/gitleaks-action#v2-benefits). Let us know if you have any questions!

https://github.com/CMSgov/qpp-file-upload-api-client/blob/ac41419e26aa84dd96bcbeea186e72ad8a8872a8/.github/workflows/git-leaks.yml#L13

**Comment by lavioli-work** [comment]
Verified with our security team that v2 does not have any significant changes that we would need to update our github actions job to. v2 requires a license and none of the features are security related.
We are keeping v1.6 and will be closing out on this issue
